modLoader = "javafml" #mandatory
loaderVersion = "[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "MIT" #Cambiar

[[mods]]
modId = "cobbleutils"
version = "1.1.1"
displayName = "CobbleUtils"
logoFile = "icon.png"
authors = ["zonary123"]
displayURL = "https://github.com/zonary123/CobbleUtils"
description = '''
A utility mod for Cobblemon.
'''

[[dependencies.cobbleutils]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[43,)" #mandatory
ordering = "NONE"
side = "BOTH"
[[dependencies.cobbleutils]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,]"
ordering = "NONE"
side = "BOTH"
[[dependencies.cobbleutils]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.5.2,]"
ordering = "AFTER"
side = "BOTH"