architectury {
    common("fabric")
    common("neoforge")
}

loom {
    accessWidenerPath = file("src/main/resources/minecraft_access.accesswidener")
}

dependencies {

    modImplementation("com.cobblemon:fabric:${property("cobblemon_version")}")
    // alL fabric dependencies:
    modImplementation("net.fabricmc:fabric-loader:${property("fabric_loader_version")}")
    modImplementation("net.fabricmc.fabric-api:fabric-api:${property("fabric_version")}")
    //modImplementation("net.neoforged:neoforge:${rootProject.neoforge_version}")

    modImplementation("dev.architectury:architectury:${property("architectury_version")}")
    modImplementation("ca.landonjw.gooeylibs:fabric-api-repack:${property("gooeylibs_version")}")


    // PlaceholderAPI
    modImplementation("eu.pb4:placeholder-api:${property("placeholder_api_version_fabricandforge")}")

    // Database
    implementation("org.mongodb:mongodb-driver-sync:${property("mongodb_version")}")
    implementation("org.xerial:sqlite-jdbc:${property("sqlite_version")}")

    // Lombok
    annotationProcessor("org.projectlombok:lombok:${property("lombok_version")}")
    implementation("org.projectlombok:lombok:${property("lombok_version")}")

    // Permissions
    api("net.luckperms:api:${property("luckperms_version")}")
    modImplementation("me.lucko:fabric-permissions-api:0.3.3")

    // Economy
    // Economy Impactor
    implementation("net.impactdev.impactor.api:economy:${property("impactor_version")}")
    api(files("libs/blanketeconomy-1.4.jar"))
    api(files("libs/cobbledollars-fabric-2.0.0-BETA1+1.21.1.jar"))
    api(files("libs/pebbles-economy-1.0.1-1.21.1.jar"))
    api("org.spigotmc:spigot-api:${property("spigot_version")}")
    api("com.github.MilkBowl:VaultAPI:${property("vault_api_version")}")
    modImplementation(files("libs/sdm-economy-common-1.21-1.6.4.jar"))

    // Kyori Adventure
    api("net.kyori:adventure-text-serializer-gson:${property("kyori_version")}")
    api("net.kyori:adventure-text-minimessage:${property("kyori_version")}")
    //api("net.kyori:adventure-platform-mod-shared-fabric-repack:6.1.0")
    //api("net.kyori:adventure-platform-mod-shared:6.1.0")

    //Discord
    api("club.minnced:discord-webhooks:${property("discord_webhooks_version")}")

    // Calculator API
    api("net.objecthunter:exp4j:0.4.8")

    // Polymer
    modImplementation("eu.pb4:polymer-core:${property("polymer_core_version")}")

    // ! Tests
    testCompileOnly 'org.projectlombok:lombok:1.18.30'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.30'

    // dependent on log4j for dynamic changing
    implementation 'org.apache.logging.log4j:log4j-api:2.22.1'
    implementation 'org.apache.logging.log4j:log4j-core:2.22.1'

    // Unit test dependencies
    testImplementation "org.junit.jupiter:junit-jupiter:5.10.0"
    testImplementation "org.junit.jupiter:junit-jupiter-params:5.10.0"
    testImplementation "org.assertj:assertj-core:3.24.2"
    testImplementation "org.mockito:mockito-core:5.4.0"
    testImplementation "org.mockito:mockito-junit-jupiter:5.4.0"

    // benchmark dependencies
    testImplementation "org.openjdk.jmh:jmh-core:1.37"
    testAnnotationProcessor "org.openjdk.jmh:jmh-generator-annprocess:1.37"
}

test {
    useJUnitPlatform()
    // Since JDK 21
    // ref: https://stackoverflow.com/questions/77951485/getting-a-java-agent-has-been-loaded-warning-in-intellij-after-upgrading-jdk-17
    jvmArgs("-XX:+EnableDynamicAgentLoading")
}


