name: Build, Discord & Modrinth Release

on:
  push:
    tags:
      - '*'

env:
  JAVA_VERSION: 21
  JAVA_DISTRIBUTION: temurin
  DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  full-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set project info
        id: set-info
        run: |
          TAG="${{ github.ref_name }}"
          MOD_NAME=$(grep '^mod_name=' gradle.properties | cut -d'=' -f2)
          MOD_VERSION=$(grep '^mod_version=' gradle.properties | cut -d'=' -f2)
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "MOD_NAME=$MOD_NAME" >> $GITHUB_ENV
          echo "MOD_VERSION=$MOD_VERSION" >> $GITHUB_ENV

      - uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}

      - uses: gradle/actions/setup-gradle@v4
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - run: chmod +x ./gradlew

      - name: Build with Gradle
        run: |
          sed -i 's/^org.gradle.java.home=/#&/' gradle.properties
          ./gradlew clean build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ env.MOD_NAME }} v${{ env.MOD_VERSION }}"
          files: |
            actual_versions/*.jar
            fabric/build/libs/*.jar
            neoforge/build/libs/*.jar
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
